from . import available_report_list
from . import report_base
from . import report_num1
from . import report_num2
from . import report_num3
from . import report_num4
from . import report_num5
from . import report_num6
from . import report_num7
from . import report_num8
from . import report_num9
from . import report_num10
from . import report_num11
from . import report_num12
from . import report_num13
from . import report_num14
from . import report_num15
from . import report_num16
from . import report_num17
from . import report_num18
from . import report_num19
from . import report_num20
from . import report_num21
from . import report_num22
from . import report_num23
from . import report_num24
