from . import res_company
from . import res_config_settings
from . import journal
from . import product
from . import point_promotion
from . import promotion_program
from . import member_card
from . import pos_order
from . import account_move
from . import stock_move
