from . import purchase_request
from . import purchase_order
from . import pos_order
from . import sale_order
from . import other_in_out_request
from . import stock_picking
from . import stock_transfer_request
from . import stock_transfer
from . import split_product
from . import transfer_stock_inventory
from . import stock_inventory
from . import hr_asset_transfer
from . import defective_product
