from . import pos_order
from . import pos_order_line
from . import contact
from . import partner_history_point
from . import pos_session
from . import points_promotion
from . import points_consumption_line
from . import account_move
from . import pos_order_line_discount_details
from . import point_compensate_request
