from . import sale_order
from . import res_partner
from . import product_template
from . import product_pricelist
from . import stock_picking
from . import account_move
from . import stock_move
from . import product_category
from . import stock_picking_type
from . import account_move_line
from . import account_tax