# -*- coding: utf-8 -*-
from . import hr_team
from . import res_users
from . import res_company
from . import hr_department
from . import forlife_model_mixin
from . import res_utility
from . import res_partner
from . import product_category
from . import product_product
from . import stock_warehouse
from . import account_move_line
from . import asset_location
from . import occasion_code
from . import uom_uom
from . import account_tax
from . import asset_asset
from . import res_bank
from . import res_headbank
from . import account_analytic_account
from . import product_config
from . import base_import
from . import res_ward
from . import pos_order
from . import pos_session
from . import pos_payment
from . import ir_model
from . import ir_ui_menu