from . import bravo_model
from . import res_config_settings
from . import res_partner
from . import stock_warehouse
from . import account_move
from . import product_product
from . import account_analytic_account
from . import hr_employee
from . import sale_order
from . import purchase_order
from . import product_category
from . import account_tax
