from . import bravo_model
from . import res_config_settings
from . import res_partner
from . import stock_warehouse
from . import account_analytic_account
from . import hr_employee
from . import sale_order
from . import purchase_order
from . import product_category
from . import uom_uom
from . import occasion_code
from . import stock_move
from . import asset_location
from . import hr_asset_transfer
from . import assets_assets
from . import res_currency_rate
from . import account_move
from . import stock_warehouse
from . import product_product
