from . import product_order_cost_line
from . import product_order_exchange_rate
from . import purchase_order
from . import forlife_event
from . import forlife_production
from . import forlife_account
from . import barcode
from . import product
from . import barcode
from . import res_partner
from . import supplier_group
from . import forlife_bom
from . import stock_warehouse
from . import product_supplierinfo
from . import hr_employee
