from . import account_move_line
from . import barcode
from . import forlife_bom
from . import forlife_event
from . import forlife_production
from . import hr_employee
from . import ir_rule
from . import product_order_cost_line
from . import purchase_order
from . import product
from . import res_partner
from . import stock_warehouse
from . import product_supplierinfo
from . import stock_move
from . import production_history
from . import production_material_import
from . import stock_picking
from . import account_move